<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" ignored="0" total="5" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="8956" started-at="2022-02-11T07:11:10Z" finished-at="2022-02-11T07:11:19Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="8956" started-at="2022-02-11T07:11:10Z" finished-at="2022-02-11T07:11:19Z">
      <class name="BankingTestCases1.AddPayeeDatadriven">
        <test-method status="PASS" signature="init()[pri:0, instance:BankingTestCases1.AddPayeeDatadriven@6e1ec318]" name="init" is-config="true" duration-ms="6902" started-at="2022-02-11T02:11:03Z" finished-at="2022-02-11T02:11:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method status="PASS" signature="login()[pri:1, instance:BankingTestCases1.AddPayeeDatadriven@6e1ec318]" name="login" duration-ms="2369" started-at="2022-02-11T02:11:10Z" finished-at="2022-02-11T02:11:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="PASS" signature="addPayee(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:2, instance:BankingTestCases1.AddPayeeDatadriven@6e1ec318]" name="addPayee" duration-ms="2875" started-at="2022-02-11T02:11:13Z" data-provider="PayeeData" finished-at="2022-02-11T02:11:16Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Payee1]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[brampton20 ]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[abbbb]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[hydro]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addPayee -->
        <test-method status="FAIL" signature="addPayee(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:2, instance:BankingTestCases1.AddPayeeDatadriven@6e1ec318]" name="addPayee" duration-ms="1022" started-at="2022-02-11T02:11:16Z" data-provider="PayeeData" finished-at="2022-02-11T02:11:17Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Payee2]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[ brampton]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[abbbb]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[hydro]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [The new payee Payee1 was successfully created.] but found [The new payee Payee2 was successfully created.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [The new payee Payee1 was successfully created.] but found [The new payee Payee2 was successfully created.]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at BankingTestCases1.AddPayeeDatadriven.addPayee(AddPayeeDatadriven.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addPayee -->
        <test-method status="FAIL" signature="addPayee(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:2, instance:BankingTestCases1.AddPayeeDatadriven@6e1ec318]" name="addPayee" duration-ms="957" started-at="2022-02-11T02:11:17Z" data-provider="PayeeData" finished-at="2022-02-11T02:11:18Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Payee3]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[brampton20 ]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[abbbb]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[hydro]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [The new payee Payee1 was successfully created.] but found [The new payee Payee3 was successfully created.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [The new payee Payee1 was successfully created.] but found [The new payee Payee3 was successfully created.]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at BankingTestCases1.AddPayeeDatadriven.addPayee(AddPayeeDatadriven.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addPayee -->
        <test-method status="FAIL" signature="addPayee(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:2, instance:BankingTestCases1.AddPayeeDatadriven@6e1ec318]" name="addPayee" duration-ms="1001" started-at="2022-02-11T02:11:18Z" data-provider="PayeeData" finished-at="2022-02-11T02:11:19Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Payee4]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[brampton20 ]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[abbbb]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[hydro]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [The new payee Payee1 was successfully created.] but found [The new payee Payee4 was successfully created.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [The new payee Payee1 was successfully created.] but found [The new payee Payee4 was successfully created.]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at BankingTestCases1.AddPayeeDatadriven.addPayee(AddPayeeDatadriven.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addPayee -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:BankingTestCases1.AddPayeeDatadriven@6e1ec318]" name="tearDown" is-config="true" duration-ms="4255" started-at="2022-02-11T02:11:19Z" finished-at="2022-02-11T02:11:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- BankingTestCases1.AddPayeeDatadriven -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
